-- MySQL Script generated by MySQL Workbench
-- Tue Nov 12 10:56:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema electromodule
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema electromodule
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `electromodule` DEFAULT CHARACTER SET utf8 ;
USE `electromodule` ;

-- -----------------------------------------------------
-- Table `electromodule`.`battery_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electromodule`.`battery_data` ;

CREATE TABLE IF NOT EXISTS `electromodule`.`battery_data` (
	id_battery_data INTEGER NOT NULL AUTO_INCREMENT UNIQUE ,
	client_id VARCHAR(255),
	soc INTEGER,
	temp INTEGER,
	timestamp DATETIME,
	PRIMARY KEY (id_battery_data)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electromodule`.`rele_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electromodule`.`rele_data` ;

CREATE TABLE IF NOT EXISTS `electromodule`.`rele_data` (
	id_rele_data INTEGER NOT NULL AUTO_INCREMENT UNIQUE ,
	rele_id VARCHAR(255),
	state BOOLEAN,
	manual BOOLEAN,
	timestamp DATETIME,
	PRIMARY KEY (id_rele_data)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
